### PR TITLE
MK Implemented BasicCourseTableIndexPage and corresponding test

### PR DESCRIPTION
**Pull request by mariekarpinska**
Implemented BasicCourseSearchIndexPage.js so that it can be moved from the homepage into a separate page clickable from the menu bar. Additionally, implemented a test for the index page, BasicCourseSearchIndexPage.test.js. 
These will be used to close issue 9: Swap the Section Search and the Description Search, which @masonma21 is closing by adapting AppNavBar and App.js and AppNavBar test to reflect the swap of basic course description search (from the homepage) and section search (from the menu bar).

Passed all frontend tests:
Screen Shot 2022-11-17 at 6 04 32 PM

Achieved Code Coverage: 
Screen Shot 2022-11-17 at 6 05 14 PM

### CODE REVIEW

**Comment by Abelatnafu** [comment]
Everything looks great to me. LGTM.

**Review by pconrad — COMMENTED** [review]
This PR adds a new page, but there is no way to access this new page yet, so it can't be tested in the app.

But what you *could* do (and should do so that this can be tested), is to add a story for it in the storybook.

I've done that for you this time.

That way once this job finishes: 

image

At the -docs-qa site, you'll have a link to the storybook entry that you can include in the PR description like this:

image

And this link takes you to the new page:

https://ucsb-cs156-f22.github.io/f22-7pm-courses-docs-qa/storybook-qa/MKandMM-SwapSectionCourseDescription/?path=/story/pages-basiccoursesearch-basiccoursesearchindexpage--default

**Review by pconrad — DISMISSED** [review]
I added a storybook entry.. that's the only problem with the original PR.  I took care of it for you this time to show how it's done; next time I'll ask the team to do it.

**Review by Abelatnafu — DISMISSED** [review]
LGTM.

**Pull request merged**
