### PR TITLE
MM&MK-SwapSearch

### LINKED ISSUE #9: Swap the Section Search and the Description Search
The home page currently offers a course search that only returns course descriptions.

Meanwhile, there is a section search on the menu bar.

We want these to swap places.

Call the new menu item: Course Descriptions

Move the Section search so that it appears on the main home page.

Adjust all tests appropriately.

### PR DESCRIPTION
**Pull request by masonma21**
Swap the section search and the description search. 

Close #9

### CODE REVIEW

**Comment by masonma21** [comment]
Close #9 

Switches the Section Search page and the Courses (Description) Search page.

The home page now will show the UCSB Section Search page:

image

image

When we click on "Search", it will show as follows and navigate to the Description search page (originally the Home page):

image

**Review by junhwanlee2316 — APPROVED** [review]
LGTM!

**Review by Abelatnafu — APPROVED** [review]
LGTM

**Review by andrewpengucsb — APPROVED** [review]
LGTM

**Pull request merged**
