### PR TITLE
Changed 'Example' brand to say UCSB Courses Search f22-7PM-2

### LINKED ISSUE #1: Fix Brand
On the main navbar, the "brand" says "Example". Change this to say "UCSB Courses Search"

Image

That's it.

estimate: 5 points

### PR DESCRIPTION
**Pull request by EthanEpp**
image
Changed Example brand to say "UCSB Courses Search"

### CODE REVIEW

**Review by pconrad — DISMISSED** [review]
Why are you commiting a change that deletes the .env.SAMPLE?

That's not good.  If we merge this, that file goes away for EVERYONE, FOREVER.

We need that file.

This is the danger of doing `git add .` without being careful.

Please bring that file back; this is not mergeable in its current form.

**Comment by pconrad** [comment]
Also: please add your team's label

**Comment by EthanEpp** [comment]
Added the .env.SAMPLE file back and added team name to PR

**Review by andrewpengucsb — APPROVED** [review]
LGTM, again please add team label

**Review by HansonYu23 — APPROVED** [review]
LGTM! Added team Label

**Pull request merged**
