### PR TITLE
Try fixing Job problem

### LINKED ISSUE #29: BUG: update courses job ui, first use fails
Overview

This is a very niche bug, and one that may be difficult to set up. But if we can fix it, we should.

On the first attempt to use the Update Courses Job after the app is deployed, if you go to the form and DO NOT change the department from what is there as the default, the first time you try to submit, it doesn't work. More detailed STR below, and an animation of the bug.

Steps to Reproduce (STR)

- Redeploy the Heroku app so that you are visiting it for the first time after a fresh deploy. (This may or may not be necessary, but it's the only time I've seen the bug happen.
- Go to the Admin / Manage Jobs page
- Select Update Courses. DO NOT CHANGE the SubjectArea; use the one that's there on the drop down.
- Click to submit the job.
- Desired Behavior: the job is submitted.
- Observed Behavior: an error toast comes up, and it is clear that the URL that the frontend is using to try to submit the job is incorrect; in particular, instead of passing the subjectArea code (e.g. ANTH) as a string, it's being passed an Object, which when converted to a String, results in an incorrect URL.

Image

### PR DESCRIPTION
**Pull request by Abelatnafu**
Abel Atnafu
- [x] Changed Update Courses Job to give the Desired Behavior that the job is submitted when initially deployed to heroku. 
Screenshot 2022-11-28 at 2 41 28 PM

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
LGTM!

**Review by masonma21 — APPROVED** [review]
LGTM！

**Review by KennethBuii — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
